### ISSUE TITLE
problems installing groovy on openSUSE

### ISSUE THREAD

**Issue by pwnage101** [ros-infrastructure/rosdep#220]
In openSUSE I'm trying to resolve build dependencies for the catkin workspace (see section 2.1.2 in the groovy installation guide for Fedora). I am to run this command:
```
$ rosdep install --from-paths src --ignore-src --rosdistro groovy -y
```
but it could not detect my OS, and asked that I provide the stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rosdep2/main.py", line 116, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/main.py", line 257, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/main.py", line 334, in _package_args_handler
    lookup = _get_default_RosdepLookup(options)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/main.py", line 107, in _get_default_RosdepLookup
    verbose=options.verbose)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/sources_list.py", line 497, in create_default
    matcher = DataSourceMatcher.create_default(os_override=os_override)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/sources_list.py", line 229, in create_default
    os_name, os_version, os_codename = os_detect.detect_os()
  File "/usr/local/lib/python2.7/site-packages/rospkg/os_detect.py", line 416, in detect_os
    raise OsNotDetected("Could not detect OS, tried %s"%attempted)
OsNotDetected: Could not detect OS, tried ['ubuntu', 'rhel', 'osx', 'opensuse', 'mint', 'gentoo', 'freebsd', 'fedora', 'debian', 'cygwin', 'arch']
```
So, I ran this command to override the OS:
```
$ ROS_OS_OVERRIDE=opensuse \
rosdep install --from-paths src --ignore-src --rosdistro groovy -y
```
but then there was an internal error:
```
Bad installer [zypper]: execv() arg 2 must contain only strings
```

(I'm on openSUSE Tumbleweed, but this is the same zypper version as openSUSE 12.2)

**Comment by tfoote** [comment]
fix merged in #281
