### ISSUE TITLE
Rosdep experienced an internal error: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by nicholsonae** [ros-infrastructure/rosdep#254]
Hello,

I currently have python-rosdep version 0.10.15-1. While trying to install ROSAria I got the error messages just below. 

rosdep install ROSARIA
WARNING: Package name "ROSARIA" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.

ERROR: Rosdep experienced an internal error: 'str' object does not support item assignment
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/main.py", line 118, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/main.py", line 259, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/main.py", line 343, in _package_args_handler
    return command_handlers[command](lookup, packages, options)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/main.py", line 508, in command_install
    uninstalled, errors = installer.get_uninstalled(packages, implicit=options.recursive, verbose=options.verbose)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/installers.py", line 401, in get_uninstalled
    resolutions, errors = self.lookup.resolve_all(resources, installer_context, implicit=implicit)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/lookup.py", line 364, in resolve_all
    rosdep_keys = self.get_rosdeps(resource_name, implicit=implicit)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/lookup.py", line 286, in get_rosdeps
    return self.loader.get_rosdeps(resource_name, implicit=implicit)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/rospkg_loader.py", line 128, in get_rosdeps
    m = self._rospack.get_manifest(resource_name)
  File "/usr/local/lib/python2.7/dist-packages/rospkg-1.0.19-py2.7.egg/rospkg/rospack.py", line 133, in get_manifest
    return self._load_manifest(name)
  File "/usr/local/lib/python2.7/dist-packages/rospkg-1.0.19-py2.7.egg/rospkg/rospack.py", line 172, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name)
  File "/usr/local/lib/python2.7/dist-packages/rospkg-1.0.19-py2.7.egg/rospkg/manifest.py", line 376, in parse_manifest_file
    _static_rosdep_view = init_rospack_interface()
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/rospack.py", line 59, in init_rospack_interface
    return lookup.get_rosdep_view(DEFAULT_VIEW_KEY)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/lookup.py", line 585, in get_rosdep_view
    view = self.create_rosdep_view(view_key, dependencies + [view_key], verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/lookup.py", line 530, in create_rosdep_view
    view.merge(db_entry, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/lookup.py", line 214, in merge
    db[dep_name].reverse_merge(dep_data, update_entry.origin, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.18-py2.7.egg/rosdep2/lookup.py", line 80, in reverse_merge
    self.data[os_name] = rules
TypeError: 'str' object does not support item assignment

Thanks for any help you can give,
Arwen

**Comment by lamhung81** [comment]
You should run:
sudo rosdep fix-permissions

then:

sudo rosdep fix-permission

**Comment by wombat-sdu** [comment]
This question is 4 years old. But thanks anyway.
