### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 205: ordinal not in range(128) on "rosdep install"

### ISSUE THREAD

**Issue by robstolarz** [ros-infrastructure/rosdep#309]
While following http://wiki.ros.org/hydro/Installation/Source to get Desktop-Full Install on Arch Linux 3.13.5-1-ARCH, I get this error:
```
[rob@Archie ros_catkin_ws]$ rosdep install --from-paths src --ignore-src --rosdistro hydro -y

ERROR: Rosdep experienced an error: 'ascii' codec can't decode byte 0xc3 in position 205: ordinal not in range(128)
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.10.25

Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/rosdep2/main.py", line 121, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python3.3/site-packages/rosdep2/main.py", line 266, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python3.3/site-packages/rosdep2/main.py", line 315, in _package_args_handler
    pkgs = find_catkin_packages_in(path, options.verbose)
  File "/usr/lib/python3.3/site-packages/rosdep2/catkin_packages.py", line 33, in find_catkin_packages_in
    packages = find_packages(path)
  File "/usr/lib/python3.3/site-packages/catkin_pkg/packages.py", line 87, in find_packages
    package = parse_package(os.path.join(basepath, path))
  File "/usr/lib/python3.3/site-packages/catkin_pkg/package.py", line 317, in parse_package
    return parse_package_string(f.read(), filename)
  File "/usr/lib/python3.3/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 205: ordinal not in range(128)



```

**Comment by triffid** [comment]
Was this ever solved? I ran into it today, while following http://wiki.ros.org/jade/Installation/Gentoo -

    ~/Projects/ros_catkin_ws $ rosdep install --from-paths src --ignore-src --rosdistro jade -y

    ERROR: Rosdep experienced an error: 'ascii' codec can't decode byte 0xc5 in position 366: ordinal not in range(128)
    Please go to the rosdep page [1] and file a bug report with the stack trace below.
    [1] : http://www.ros.org/wiki/rosdep

    rosdep version: 0.11.2

    Traceback (most recent call last):
    File "/usr/lib64/python3.3/site-packages/rosdep2/main.py", line 136, in rosdep_main
        exit_code = _rosdep_main(args)
    File "/usr/lib64/python3.3/site-packages/rosdep2/main.py", line 345, in _rosdep_main
        return _package_args_handler(command, parser, options, args)
    File "/usr/lib64/python3.3/site-packages/rosdep2/main.py", line 394, in _package_args_handler
        pkgs = find_catkin_packages_in(path, options.verbose)
    File "/usr/lib64/python3.3/site-packages/rosdep2/catkin_packages.py", line 33, in find_catkin_packages_in
        packages = find_packages(path)
    File "/usr/lib64/python3.3/site-packages/catkin_pkg/packages.py", line 83, in find_packages
        packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
    File "/usr/lib64/python3.3/site-packages/catkin_pkg/packages.py", line 110, in find_packages_allowing_duplicates
        packages[path] = parse_package(os.path.join(basepath, path), warnings=warnings)
    File "/usr/lib64/python3.3/site-packages/catkin_pkg/package.py", line 370, in parse_package
        return parse_package_string(f.read(), filename, warnings=warnings)
    File "/usr/lib64/python3.3/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 366: ordinal not in range(128)

    $ python -c "import catkin_pkg; print(catkin_pkg.__version__)"
    0.2.10
    $ env | grep -P "LANG|LC"
    (no result)
    $ python -c "import sys; print(sys.version); print(sys.getdefaultencoding())"
    3.3.5 (default, Nov 19 2014, 13:44:53) 
    [GCC 4.7.3]
    utf-8
    $ wget https://raw.github.com/ethz-asl/map_msgs/master/package.xml
    (wget output)
    $ python -c "from catkin_pkg.package import parse_package_string; parse_package_string(open('package.xml', 'r').read())"
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib64/python3.3/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 205: ordinal not in range(128)
    $ python -c "f = open('package.xml', 'r'); f.read()"
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib64/python3.3/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 205: ordinal not in range(128)
    $ python -c "import locale; print(locale.getpreferredencoding(False))"
    ANSI_X3.4-1968
    $ locale
    LANG=
    LC_CTYPE="POSIX"
    LC_NUMERIC="POSIX"
    LC_TIME="POSIX"
    LC_COLLATE="POSIX"
    LC_MONETARY="POSIX"
    LC_MESSAGES="POSIX"
    LC_PAPER="POSIX"
    LC_NAME="POSIX"
    LC_ADDRESS="POSIX"
    LC_TELEPHONE="POSIX"
    LC_MEASUREMENT="POSIX"
    LC_IDENTIFICATION="POSIX"
    LC_ALL=
    $ locale -a
    C
    POSIX
    en_US
    en_US.iso88591
    en_US.utf8

**Comment by de-vri-es** [comment]
Note that this is a problem in `catkin_pkg` and not in `rosdep` itself.

I believe ros-infrastructure/catkin_pkg#143 should fix this.
