### ISSUE TITLE
rosdep complains about missing url

### ISSUE THREAD

**Issue by bricerebsamen** [ros-infrastructure/rosdep#320]
I'm trying to release the diagnostics stack into indigo but the pre-release test fails:
http://jenkins.ros.org/job/prerelease-hydro-diagnostics/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=prerelease/1/

it complains about missing URL. I checked diagnostics/package.xml and it has a url tag. I tried adding the repository and bugtracker url, but that does not seem to help.

$ rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://github.com/ros/rosdistro/raw/master/rosdep/osx-homebrew.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/gentoo.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/base.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/python.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/ruby.yaml
Hit https://github.com/ros/rosdistro/raw/master/releases/fuerte.yaml
Ignore legacy gbpdistro "groovy"
ERROR: unable to process source [file://localhost/data/driving_repos/catkin_ws/src/rdr_v2/scripts/rosdep.yaml]:
    <urlopen error [Errno 2] No such file or directory: '/data/driving_repos/catkin_ws/src/rdr_v2/scripts/rosdep.yaml'> (file://localhost/data/driving_repos/catkin_ws/src/rdr_v2/scripts/rosdep.yaml)
Query rosdistro index https://raw.github.com/ros/rosdistro/master/index.yaml
Add distro "groovy"
Add distro "indigo"

ERROR: Rosdep experienced an error: Repository 'diagnostics' lacks required URL information
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.10.25

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 121, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 264, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 272, in _no_args_handler
    return command_handlers[command](options)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 437, in command_update
    error_handler=update_error_handler)
  File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 436, in update_sources_list
    rosdep_data = get_gbprepo_as_rosdep_data(d)
  File "/usr/lib/pymodules/python2.7/rosdep2/gbpdistro_support.py", line 143, in get_gbprepo_as_rosdep_data
    distro_file = get_release_file(gbpdistro)
  File "/usr/lib/pymodules/python2.7/rosdep2/rosdistrohelper.py", line 76, in get_release_file
    dist_file = rosdistro.get_distribution_file(get_index(), distro)
  File "/usr/lib/pymodules/python2.7/rosdistro/__init__.py", line 128, in get_distribution_file
    return DistributionFile(dist_name, data)
  File "/usr/lib/pymodules/python2.7/rosdistro/distribution_file.py", line 57, in **init**
    repo = Repository(repo_name, repo_data.get('doc', None), repo_data.get('release', None), repo_data.get('source', None), repo_data)
  File "/usr/lib/pymodules/python2.7/rosdistro/repository.py", line 46, in **init**
    self.release_repository = ReleaseRepositorySpecification(self.name, release_data) if release_data else None
  File "/usr/lib/pymodules/python2.7/rosdistro/release_repository_specification.py", line 40, in **init**
    super(ReleaseRepositorySpecification, self).**init**(name, data)
  File "/usr/lib/pymodules/python2.7/rosdistro/repository_specification.py", line 40, in **init**
    assert 'url' in data and data['url'], "Repository '%s' lacks required URL information" % name
AssertionError: Repository 'diagnostics' lacks required URL information

**Comment by codeundercoverdev** [comment]
wait, so whats the fix? im just running `rosdep update` and getting the error
