### ISSUE TITLE
rosdep install rosaria - ERROR:  Could not detect OS (Elementary OS Luna)

### ISSUE THREAD

**Issue by arandilopez** [ros-infrastructure/rosdep#329]
I'm trying to install rosaria in Luna and the command:

```$ rosdep install rosaria```

throws this:

```
ERROR: Rosdep experienced an error: Could not detect OS, tried ['windows', 'ubuntu', 'rhel', 'qnx', 'osx', 'opensuse', 'mint', 'gentoo', 'freebsd', 'fedora', 'debian', 'cygwin', 'arch']
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.10.27

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 121, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 279, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 356, in _package_args_handler
    lookup = _get_default_RosdepLookup(options)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 112, in _get_default_RosdepLookup
    verbose=options.verbose)
  File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 560, in create_default
    matcher = DataSourceMatcher.create_default(os_override=os_override)
  File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 263, in create_default
    os_name, os_version, os_codename = os_detect.detect_os()
  File "/usr/lib/pymodules/python2.7/rospkg/os_detect.py", line 458, in detect_os
    raise OsNotDetected("Could not detect OS, tried %s"%attempted)
OsNotDetected: Could not detect OS, tried ['windows', 'ubuntu', 'rhel', 'qnx', 'osx', 'opensuse', 'mint', 'gentoo', 'freebsd', 'fedora', 'debian', 'cygwin', 'arch']
```
I will glad if some could tell me how to solve this issue...

**Comment by tfoote** [comment]
duplicate #272
