### ISSUE TITLE
Could not detect OS while rosdep update on Kali Linux

### ISSUE THREAD

**Issue by RogerWeihrauch** [ros-infrastructure/rosdep#385]
Howdy community

May be there is a hack for 'faking' the os's name, eg. to 'debian' as shown down, but I do not know where to change this for ROS.
(I followd the insall instructions fpr debian wheezy since I am runnung Kali Linux, based on Debian Wheezy:
root@kalilinux:~# uname -a
Linux kalilinux 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux
root@kalilinux:~# cat /proc/version 
Linux version 3.18.0-kali3-amd64 (debian-kernel@lists.debian.org) (gcc version 4.7.2 (Debian 4.7.2-5) ) #1 SMP Debian 3.18.6-1~kali2 (2015-03-02)
root@kalilinux:~# 
)
Any hint will be kindly appreciated.

Since I am not a programmer I am asked to also add a traceback of this messsage:

reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml
Add distro "groovy"

ERROR: Rosdep experienced an error: Could not detect OS, tried ['windows', 'ubuntu', 'rhel', 'qnx', 'osx', 'opensuse', 'opensuse', 'mint', 'linaro', 'gentoo', 'freebsd', 'fedora', 'debian', 'cygwin', 'centos', 'arch']
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.2

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 343, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 351, in _no_args_handler
    return command_handlers[command](options)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 533, in command_update
    error_handler=update_error_handler)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 466, in update_sources_list
    rosdep_data = get_gbprepo_as_rosdep_data(dist_name)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/gbpdistro_support.py", line 147, in get_gbprepo_as_rosdep_data
    ctx = create_default_installer_context()
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/__init__.py", line 85, in create_default_installer_context
    m.register_platforms(context)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/platforms/debian.py", line 50, in register_platforms
    register_linaro(context)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/platforms/debian.py", line 63, in register_linaro
    (os_name, os_version) = context.get_os_name_and_version()
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/installers.py", line 112, in get_os_name_and_version
    os_name = self.os_detect.get_name()
  File "/usr/local/lib/python2.7/dist-packages/rospkg/os_detect.py", line 518, in get_name
    self.detect_os()
  File "/usr/local/lib/python2.7/dist-packages/rospkg/os_detect.py", line 488, in detect_os
    raise OsNotDetected("Could not detect OS, tried %s"%attempted)
OsNotDetected: Could not detect OS, tried ['windows', 'ubuntu', 'rhel', 'qnx', 'osx', 'opensuse', 'opensuse', 'mint', 'linaro', 'gentoo', 'freebsd', 'fedora', 'debian', 'cygwin', 'centos', 'arch']

**Comment by tfoote** [comment]
You can use the command line option `--os=debian:wheezy` to tell rosdep what OS to use. 

Or you can use the `ROS_OS_OVERRIDE` environment varialbe by running `export ROS_OS_OVERRIDE=debian:wheezy`

There are directions for adding support for a new OS [here](http://docs.ros.org/independent/api/rosdep/html/developers_guide.html) but I think that since this is a less common OS it will probably be better for you to put the export in you `~/.bashrc` file to tell rosdep that you're running wheezy and move on. 

If you'd like more help please follow up on answers.ros.org (search first then ask if you don't find the solution)
