### ISSUE TITLE
How can I fix erorr after: sudo rosdep init???

### ISSUE THREAD

**Issue by Olenchik** [ros-infrastructure/rosdep#388]
Traceback (most recent call last):
  File "/usr/local/bin/rosdep", line 4, in <module>
    __import__('pkg_resources').run_script('rosdep==0.11.2', 'rosdep')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 735, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1644, in run_script
pkg_resources.ResolutionError: No script named 'rosdep'

**Comment by tfoote** [comment]
Asked here: http://answers.ros.org/question/214055/how-can-i-fix-rosdep-init-problem/ Please don't duplicate questions. [Support Guidelines](http://wiki.ros.org/Support)
