### ISSUE TITLE
rosdep install rgbdslam_freiburg

### ISSUE THREAD

**Issue by praveen-science** [ros-infrastructure/rosdep#389]
ERROR: Rosdep experienced an error: Invalid package manifest "/home/pi/ros_catkin_ws/pcl-release/hydro/package.xml": Package version ":{version}" does not follow version conventions
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.2

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 345, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 435, in _package_args_handler
    return command_handlers[command](lookup, packages, options)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 619, in command_install
    uninstalled, errors = installer.get_uninstalled(packages, implicit=options.recursive, verbose=options.verbose)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/installers.py", line 405, in get_uninstalled
    resolutions, errors = self.lookup.resolve_all(resources, installer_context, implicit=implicit)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/lookup.py", line 383, in resolve_all
    rosdep_keys = self.get_rosdeps(resource_name, implicit=implicit)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/lookup.py", line 305, in get_rosdeps
    return self.loader.get_rosdeps(resource_name, implicit=implicit)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/rospkg_loader.py", line 134, in get_rosdeps
    return self._rospack.get_rosdeps(resource_name, implicit=implicit)
  File "/usr/local/lib/python2.7/dist-packages/rospkg/rospack.py", line 333, in get_rosdeps
    return self._implicit_rosdeps(package)
  File "/usr/local/lib/python2.7/dist-packages/rospkg/rospack.py", line 353, in _implicit_rosdeps
    packages = self.get_depends(package, implicit=True)
  File "/usr/local/lib/python2.7/dist-packages/rospkg/rospack.py", line 236, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/local/lib/python2.7/dist-packages/rospkg/rospack.py", line 230, in get_depends
    names = [p.name for p in self.get_manifest(name).depends]
  File "/usr/local/lib/python2.7/dist-packages/rospkg/rospack.py", line 163, in get_manifest
    return self._load_manifest(name)
  File "/usr/local/lib/python2.7/dist-packages/rospkg/rospack.py", line 207, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/local/lib/python2.7/dist-packages/rospkg/manifest.py", line 376, in parse_manifest_file
    p = parse_package(package_filename)
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg/package.py", line 370, in parse_package
    return parse_package_string(f.read(), filename, warnings=warnings)
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg/package.py", line 543, in parse_package_string
    pkg.validate(warnings=warnings)
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg/package.py", line 244, in validate
    raise InvalidPackage('\n'.join(errors))
InvalidPackage: Invalid package manifest "/home/pi/ros_catkin_ws/pcl-release/hydro/package.xml": Package version ":{version}" does not follow version conventions

Can anybody help me how to solve this issue.

**Comment by wjwwood** [comment]
You've cloned an untemplated version of pcl from a release repository, that's where the `:{version}` comes from in the error message. That will not work and as is the error is correct, that is not a valid version. You need to get pcl some other way, using `rosinstall_generator` (http://wiki.ros.org/rosinstall_generator) or using apt-get if you're on Ubuntu (`sudo apt-get install ros-hydro-pcl`).

If you have further questions about how to set this up, please ask on http://answers.ros.org.
