### ISSUE TITLE
error with indigo on os x

### ISSUE THREAD

**Issue by migel** [ros-infrastructure/rosdep#425]
```
mk@mk-mbp:~/ros_ws$ rosdep install --from-paths src --ignore-src --rosdistro indigo -y

ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.4

Bad installer [homebrew]: Error while parsing brew info for 'ros/indigo/fcl'
 * Output of `brew info ros/indigo/fcl --json=v1`:

 * Error while parsing:
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rosdep2/platforms/osx.py", line 184, in is_installed
    pkg_info = json.loads(std_out)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by wjwwood** [comment]
This error occurs because there is no `fcl` package in Homebrew. One of the packages which you depend on uses `fcl`, but it is not in your local workspace of packages.
