### ISSUE TITLE
Conflict with matlab

### ISSUE THREAD

**Issue by Fragore** [ros-infrastructure/rosdep#428]
Hi, I have problem running rosdep commands because it conflicts with Matlab.

rosdep version: 0.11.4

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 353, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 406, in _package_args_handler
    pkgs = find_catkin_packages_in(path, options.verbose)
  File "/usr/lib/python2.7/dist-packages/rosdep2/catkin_packages.py", line 33, in find_catkin_packages_in
    packages = find_packages(path)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 83, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 110, in find_packages_allowing_duplicates
    packages[path] = parse_package(os.path.join(basepath, path), warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 370, in parse_package
    return parse_package_string(f.read(), filename, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 396, in parse_package_string
    raise InvalidPackage('The manifest must contain a single "package" root tag')
InvalidPackage: Invalid package manifest "/home/giuseppe/MATLAB/resources/MATLAB/ja_JP/apputil/package.xml": The manifest must contain a single "package" root tag
```

**Comment by wjwwood** [comment]
You'll have to avoid putting the MATLAB folder with a `package.xml` on your `ROS_PACKAGE_PATH` or within a path given to `rosdep`. You can also place a `CATKIN_IGNORE` file anywhere to prevent it from looking deeper in the tree under that file. See:

http://answers.ros.org/question/208180/how-to-use-catkin_ignore-file-correctly/

I do not believe there is anything to be done in `rosdep` for this issue.
