### ISSUE TITLE
Error with index version 3

### ISSUE THREAD

**Issue by erwin008** [ros-infrastructure/rosdep#435]
rosdep version: 0.10.30

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 126, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 286, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 294, in _no_args_handler
    return command_handlers[command](options)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 468, in command_update
    error_handler=update_error_handler)
  File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 433, in update_sources_list
    for dist_name in sorted(get_index().distributions.keys()):
  File "/usr/lib/pymodules/python2.7/rosdep2/rosdistrohelper.py", line 69, in get_index
    _RDCache.index = rosdistro.get_index(_RDCache.index_url)
  File "/usr/lib/pymodules/python2.7/rosdistro/__init__.py", line 115, in get_index
    return Index(data, base_url)
  File "/usr/lib/pymodules/python2.7/rosdistro/index.py", line 51, in __init__
    assert int(data['version']) == 2, "Unable to handle '%s' format version '%d', please update rosdistro (e.g. on Ubuntu/Debian use: sudo apt-get update && sudo apt-get install --only-upgrade python-rosdistro)" % (Index._type, int(data['version']))
AssertionError: Unable to handle 'index' format version '3', please update rosdistro (e.g. on Ubuntu/Debian use: sudo apt-get update && sudo apt-get install --only-upgrade python-rosdistro)

Platform:
Cubieboard 2 A20 with Linaro 12.11 based on Ubuntu 12.04

**Comment by tfoote** [comment]
You need to upgrade your rosdistro version to 0.4.0 or higher. 0.4.3 is the current released version. If you need help doing that on your platform, please ask on answers.ros.org
