### ISSUE TITLE
ERROR: Rosdep experienced an error: Multiple packages found with the same name "ros_indigosdk":

### ISSUE THREAD

**Issue by felixmn91** [ros-infrastructure/rosdep#442]
```
ERROR: Rosdep experienced an error: Multiple packages found with the same name "ros_indigosdk":
- third_party/omnicam/ros_indigosdk-pre1.2
- third_party/ros_indigosdk-1.3.8
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.4

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 353, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 428, in _package_args_handler
    pkgs = find_catkin_packages_in(path, options.verbose)
  File "/usr/lib/python2.7/dist-packages/rosdep2/catkin_packages.py", line 33, in find_catkin_packages_in
    packages = find_packages(path)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 92, in find_packages
    raise RuntimeError('\n'.join(duplicates))
RuntimeError: Multiple packages found with the same name "ros_indigosdk":
- third_party/omnicam/ros_indigosdk-pre1.2
- third_party/ros_indigosdk-1.3.8
```

**Comment by wjwwood** [comment]
You have two packages in your workspace that have the same name, as the error says. There's nothing we can change in rosdep to fix that. The suggestion to open a ticket here is a generic catch-all for any exceptions. Sorry if that mislead you into thinking it was an issue with rosdep, I'll close this.
