### ISSUE TITLE
rosdep run as root

### ISSUE THREAD

**Issue by dominiquehunziker** [ros-infrastructure/rosdep#45]
Hi,

I think there is a problem when rosdep is run as root, because root has no command sudo.

Here is the full error message:
executing command [sudo apt-get install libjson-glib-dev]

ERROR: Rosdep experienced an internal error: [Errno 2] No such file or directory
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 116, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 257, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 338, in _package_args_handler
    return command_handlers[command](lookup, packages, options)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 494, in command_install
    installer.install(uninstalled, *_install_options)
  File "/usr/lib/pymodules/python2.7/rosdep2/installers.py", line 477, in install
    verbose=verbose)
  File "/usr/lib/pymodules/python2.7/rosdep2/installers.py", line 526, in install_resolved
    result = subprocess.call(sub_command)
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(_popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by jonbinney** [comment]
Looks like rosdep now has a `--as-root` option to handle this case, so maybe this can be closed now?

**Comment by tfoote** [comment]
This has been more fully documented in #473 and that's open to track improving the error message.
