### ISSUE TITLE
rosdep experienced an error: 'list' object has no attribute 'encode'

### ISSUE THREAD

**Issue by csorice147** [ros-infrastructure/rosdep#453]
**$rosdep update**

ERROR: Rosdep experienced an error: 'list' object has no attribute 'encode'
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.10.30

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 126, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 286, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 294, in _no_args_handler
    return command_handlers\[command\](options)
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 468, in command_update
    error_handler=update_error_handler)
  File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 438, in update_sources_list
    retval.append((rds, write_cache_file(sources_cache_dir, dist['distribution'], rosdep_data)))
  File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 493, in write_cache_file
    key_hash = compute_filename_hash(filename_key)
  File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 479, in compute_filename_hash
    sha_hash.update(filename_key.encode())
AttributeError: 'list' object has no attribute 'encode'

**Comment by tfoote** [comment]
version 0.10.30 is several versions out of date. Can you please update to 0.11.4 and see if this has already been fixed?
