### ISSUE TITLE
ros full-install requires a bytes-like object on Mac Os X Yosemite

### ISSUE THREAD

**Issue by Levityx** [ros-infrastructure/rosdep#479]
Step 2.1.2 of the homebrew installation guide broke down. See the below.
Best regards, 
-- 
Alban

rosdep version: 0.11.5

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/local/lib/python3.5/site-packages/rosdep2/main.py", line 353, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/local/lib/python3.5/site-packages/rosdep2/main.py", line 447, in _package_args_handler
    return command_handlers[command](lookup, packages, options)
  File "/usr/local/lib/python3.5/site-packages/rosdep2/main.py", line 654, in command_install
    installer.install(uninstalled, **install_options)
  File "/usr/local/lib/python3.5/site-packages/rosdep2/installers.py", line 485, in install
    verbose=verbose, quiet=quiet)
  File "/usr/local/lib/python3.5/site-packages/rosdep2/installers.py", line 515, in install_resolved
    command = installer.get_install_command(resolved, interactive=interactive, reinstall=reinstall, quiet=quiet)
  File "/usr/local/lib/python3.5/site-packages/rosdep2/platforms/osx.py", line 316, in get_install_command
    resolved = self.remove_duplicate_dependencies(resolved)
  File "/usr/local/lib/python3.5/site-packages/rosdep2/platforms/osx.py", line 347, in remove_duplicate_dependencies
    if brew_strip_pkg_name(other.package) == brew_strip_pkg_name(d):
  File "/usr/local/lib/python3.5/site-packages/rosdep2/platforms/osx.py", line 157, in brew_strip_pkg_name
    return package.split('/')[-1]
TypeError: a bytes-like object is required, not 'str'
```

**Comment by wjwwood** [comment]
Hi, it looks like you're using Python 3 based on your file paths, e.g. `/usr/local/lib/python3.5/site-packages/rosdep2/platforms/osx.py`. While I expect rosdep should work with Python3, and so this error shouldn't arise, I think the larger issues is that you're using Python3 where you should be using Python2.

I've created a more generic issue here: https://github.com/ros-infrastructure/rosdep/issues/480

I'll close this one for now. If you are having trouble selecting the right Python version I recommend asking in a more generic form like answers.ros.org or perhaps consider using the instructions list here: https://github.com/mikepurvis/ros-install-osx
