### ISSUE TITLE
ERROR: Rosdep experienced an error: Unable to handle 'index' format version '3'

### ISSUE THREAD

**Issue by YannickBlais** [ros-infrastructure/rosdep#485]
On Fedora24, using robotpkg, following hints trying to compile ORB_SLAM2's ROS examples:

```
[rosbuild] Building package ORB_SLAM2
Failed to invoke /opt/robotpkg/bin/rospack deps-manifests ORB_SLAM2
[rospack] Error: the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'

```
sudo rosdep init works but rosdep update causes this ouput:
```
reading in sources list data from /opt/robotpkg/etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.github.com/ros/rosdistro/master/index.yaml

ERROR: Rosdep experienced an error: Unable to handle 'index' format version '3', please update rosdistro (e.g. on Ubuntu/Debian use: sudo apt-get update && sudo apt-get install --only-upgrade python-rosdistro)
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.10.30

Traceback (most recent call last):
  File "/opt/robotpkg/lib/python2.7/site-packages/rosdep2/main.py", line 126, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/opt/robotpkg/lib/python2.7/site-packages/rosdep2/main.py", line 286, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
  File "/opt/robotpkg/lib/python2.7/site-packages/rosdep2/main.py", line 294, in _no_args_handler
    return command_handlers[command](options)
  File "/opt/robotpkg/lib/python2.7/site-packages/rosdep2/main.py", line 468, in command_update
    error_handler=update_error_handler)
  File "/opt/robotpkg/lib/python2.7/site-packages/rosdep2/sources_list.py", line 433, in update_sources_list
    for dist_name in sorted(get_index().distributions.keys()):
  File "/opt/robotpkg/lib/python2.7/site-packages/rosdep2/rosdistrohelper.py", line 69, in get_index
    _RDCache.index = rosdistro.get_index(_RDCache.index_url)
  File "/opt/robotpkg/lib/python2.7/site-packages/rosdistro/__init__.py", line 115, in get_index
    return Index(data, base_url)
  File "/opt/robotpkg/lib/python2.7/site-packages/rosdistro/index.py", line 51, in __init__
    assert int(data['version']) == 2, "Unable to handle '%s' format version '%d', please update rosdistro (e.g. on Ubuntu/Debian use: sudo apt-get update && sudo apt-get install --only-upgrade python-rosdistro)" % (Index._type, int(data['version']))
AssertionError: Unable to handle 'index' format version '3', please update rosdistro (e.g. on Ubuntu/Debian use: sudo apt-get update && sudo apt-get install --only-upgrade python-rosdistro)
```
I tried to pip --upgrade rosdistro using what is given here](http://answers.ros.org/question/122266/how-can-i-fix-unable-to-handle-index-format-version-2-please-update-rosdistro/) but to no avail

**Comment by tfoote** [comment]
The robotpkg versions appear to be noteably out of date. rosdep is currently in version 0.11.5 while you're is reporting 0.10.30. 0.10.30 was released in 2014. Likely your rosdistro version is similarly out of date. 

A generic pip installing is not going to work since if you look at the path, it's using the version in `/opt/rosbotpkg` not the version pip installed. You need to update the version on your path as installed by robotpkg. You can likely invoke pip appropriately to overlay your robotpkg installation. But I'd recommend opening a ticket with robotpkg to get the versions of rosdistro and rosdep updated.
