### ISSUE TITLE
ERROR: Rosdep experienced an error: Invalid package manifest "/opt/ros/indigo/share/roslang/package.xml"

### ISSUE THREAD

**Issue by fhfonsecaa** [ros-infrastructure/rosdep#488]
I just installed ROS indigo on my Raspbery Pi 3 and I have this error all the time.

pi@raspberrypi:~/ros_catkin_ws` $ rosdep install --from-paths src --ignore-src --rosdistro indigo -y -r --os=debian:jessie

ERROR: Rosdep experienced an error: Invalid package manifest "/opt/ros/indigo/share/roslang/package.xml": The manifest contains invalid XML:
no element found: line 1, column 0
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.5

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 353, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/main.py", line 428, in _package_args_handler
    pkgs = find_catkin_packages_in(path, options.verbose)
  File "/usr/local/lib/python2.7/dist-packages/rosdep2/catkin_packages.py", line 33, in find_catkin_packages_in
    packages = find_packages(path)
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 83, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 110, in find_packages_allowing_duplicates
    packages[path] = parse_package(os.path.join(basepath, path), warnings=warnings)
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg/package.py", line 370, in parse_package
    return parse_package_string(f.read(), filename, warnings=warnings)
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg/package.py", line 389, in parse_package_string
    raise InvalidPackage('The manifest contains invalid XML:\n%s' % ex)
InvalidPackage: Invalid package manifest "/opt/ros/indigo/share/roslang/package.xml": The manifest contains invalid XML:
no element found: line 1, column 0

**Comment by wjwwood** [comment]
Are the contents of `/opt/ros/indigo/share/roslang/package.xml` valid? I'd say that you have a file corruption issue. You can also make sure that your `python-rosdep` and `python-rosdistro` packages are up-to-date.
