### ISSUE TITLE
rosdep does not use os_override in all code paths

### ISSUE THREAD

**Issue by kchristofferson** [ros-infrastructure/rosdep#51]
Was: Failed to detect wheezy OS running rosdep on raspberry 

I was stepping through the generic source installation steps to try and install groovy on a raspberry pi.

At step 2.1.3 I ran the command rosdep and failed to find (in my case override) the OS.

```
pi@raspberrypi ~/ros_catkin_ws $ rosdep install --os=debian:wheezy --from-paths src --ignore-src --rosdistro groovy -y

ERROR: Rosdep experienced an internal error: Could not detect OS, tried ['ubuntu', 'rhel', 'osx', 'opensuse', 'mint', 'gentoo', 'freebsd', 'fedora', 'debian', 'cygwin', 'arch']
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/main.py", line 116, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/main.py", line 257, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/main.py", line 338, in _package_args_handler
    return command_handlers[command](lookup, packages, options)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/main.py", line 483, in command_install
    uninstalled, errors = installer.get_uninstalled(packages, implicit=options.recursive, verbose=options.verbose)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/installers.py", line 401, in get_uninstalled
    resolutions, errors = self.lookup.resolve_all(resources, installer_context, implicit=implicit)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/lookup.py", line 348, in resolve_all
    rosdep_keys = self.get_rosdeps(resource_name, implicit=implicit)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/lookup.py", line 270, in get_rosdeps
    return self.loader.get_rosdeps(resource_name, implicit=implicit)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/rospkg_loader.py", line 128, in get_rosdeps
    m = self._rospack.get_manifest(resource_name)
  File "/usr/local/lib/python2.7/dist-packages/rospkg-1.0.17-py2.7.egg/rospkg/rospack.py", line 133, in get_manifest
    return self._load_manifest(name)
  File "/usr/local/lib/python2.7/dist-packages/rospkg-1.0.17-py2.7.egg/rospkg/rospack.py", line 172, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name)
  File "/usr/local/lib/python2.7/dist-packages/rospkg-1.0.17-py2.7.egg/rospkg/manifest.py", line 376, in parse_manifest_file
    _static_rosdep_view = init_rospack_interface()
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/rospack.py", line 55, in init_rospack_interface
    lookup = _get_default_RosdepLookup(Options())
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/main.py", line 107, in _get_default_RosdepLookup
    verbose=options.verbose)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/sources_list.py", line 497, in create_default
    matcher = DataSourceMatcher.create_default(os_override=os_override)
  File "/usr/local/lib/python2.7/dist-packages/rosdep-0.10.11-py2.7.egg/rosdep2/sources_list.py", line 229, in create_default
    os_name, os_version, os_codename = os_detect.detect_os()
  File "/usr/local/lib/python2.7/dist-packages/rospkg-1.0.17-py2.7.egg/rospkg/os_detect.py", line 405, in detect_os
    raise OsNotDetected("Could not detect OS, tried %s"%attempted)
OsNotDetected: Could not detect OS, tried ['ubuntu', 'rhel', 'osx', 'opensuse', 'mint', 'gentoo', 'freebsd', 'fedora', 'debian', 'cygwin', 'arch']
```

**Comment by mkatliar** [comment]
The issue affects me as well https://github.com/ros-infrastructure/rosdep/issues/890#issuecomment-1328393948
