### ISSUE TITLE
Yaml parsing error

### ISSUE THREAD

**Issue by martiniil** [ros-infrastructure/rosdep#684]
There seems to be a "tab" in a yaml-file somewhere, but I could not find it.
This occured on Jenkins: http://build.ros.org/job/Kdoc__pilz_robots__ubuntu_xenial_amd64/2/

```
rosdep version: 0.15.2
18:11:20 
18:11:20 Traceback (most recent call last):
18:11:20   File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 140, in rosdep_main
18:11:20     exit_code = _rosdep_main(args)
18:11:20   File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 394, in _rosdep_main
18:11:20     return _no_args_handler(command, parser, options, args)
18:11:20   File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 403, in _no_args_handler
18:11:20     return command_handlers[command](options)
18:11:20   File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 601, in command_update
18:11:20     skip_eol_distros=not options.include_eol_distros)
18:11:20   File "/usr/lib/python3/dist-packages/rosdep2/sources_list.py", line 497, in update_sources_list
18:11:20     rosdep_data = get_gbprepo_as_rosdep_data(dist_name)
18:11:20   File "/usr/lib/python3/dist-packages/rosdep2/gbpdistro_support.py", line 149, in get_gbprepo_as_rosdep_data
18:11:20     distro_file = get_release_file(gbpdistro)
18:11:20   File "/usr/lib/python3/dist-packages/rosdep2/rosdistrohelper.py", line 76, in get_release_file
18:11:20     dist_file = rosdistro.get_distribution_file(get_index(), distro)
18:11:20   File "/usr/lib/python3/dist-packages/rosdistro/__init__.py", line 119, in get_distribution_file
18:11:20     data = _get_dist_file_data(index, dist_name, 'distribution')
18:11:20   File "/usr/lib/python3/dist-packages/rosdistro/__init__.py", line 202, in _get_dist_file_data
18:11:20     data.append(_load_yaml_data(u))
18:11:20   File "/usr/lib/python3/dist-packages/rosdistro/__init__.py", line 195, in _load_yaml_data
18:11:20     return yaml.safe_load(yaml_str)
18:11:20   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 94, in safe_load
18:11:20     return load(stream, SafeLoader)
18:11:20   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
18:11:20     return loader.get_single_data()
18:11:20   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 35, in get_single_data
18:11:20     node = self.get_single_node()
18:11:20   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
18:11:20     document = self.compose_document()
18:11:20   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
18:11:20     node = self.compose_node(None, None)
18:11:20   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
18:11:20     node = self.compose_mapping_node(anchor)
18:11:20   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
18:11:20     item_value = self.compose_node(node, item_key)
18:11:20   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
18:11:20     node = self.compose_mapping_node(anchor)
18:11:20   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
18:11:20     item_value = self.compose_node(node, item_key)
18:11:20   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
18:11:20     node = self.compose_mapping_node(anchor)
18:11:20   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
18:11:20     item_value = self.compose_node(node, item_key)
18:11:20   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 64, in compose_node
18:11:20     if self.check_event(AliasEvent):
18:11:20   File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
18:11:20     self.current_event = self.state()
18:11:20   File "/usr/lib/python3/dist-packages/yaml/parser.py", line 449, in parse_block_mapping_value
18:11:20     if not self.check_token(KeyToken, ValueToken, BlockEndToken):
18:11:20   File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 116, in check_token
18:11:20     self.fetch_more_tokens()
18:11:20   File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 257, in fetch_more_tokens
18:11:20     self.get_mark())
18:11:20 yaml.scanner.ScannerError: while scanning for the next token
18:11:20 found character '\t' that cannot start any token
18:11:20   in "<unicode string>", line 226, column 9:
18:11:20         doc:	
18:11:20             ^
```

**Comment by tfoote** [comment]
There was a temporarily malformatted entry in the rosdistro that has been resolved. The build is now back to functional. Thanks for checking on the build breakage. You couldn't find the tab as this was temporarily running off of a forked version while we stood up the new version of the buildfarm.
