### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by xytmisscwj** [ros-infrastructure/rosdep#688]
rosdep version: 0.15.2

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 140, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 394, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 403, in _no_args_handler
    return command_handlers[command](options)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 601, in command_update
    skip_eol_distros=not options.include_eol_distros)
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 479, in update_sources_list
    retval.append((source, write_cache_file(sources_cache_dir, source.url, rosdep_data)))
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 563, in write_cache_file
    os.makedirs(source_cache_d)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/chris/.ros/rosdep'

**Comment by sloretz** [comment]
> `OSError: [Errno 13] Permission denied: '/home/chris/.ros/rosdep'`

Hi @xytmisscwj, this looks like an issue with the home folder permissions. Does the path `/home/chris` exist? If so, is it owned by the current user?

Sometimes I see this with [osrf/rocker](https://github.com/osrf/rocker) when using the `--user` option. It doesn't create a home folder, but that can be fixed with `sudo chown chris:chris /home/chris`.

I'll close this issue since it doesn't seem like it is a `rosdep` bug.
