### ISSUE TITLE
Please add Zorin OS to the list of Rosdep sources

### ISSUE THREAD

**Issue by bartblommaerts** [ros-infrastructure/rosdep#696]
Stack trace:
rosdep version: 0.15.2

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 140, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 394, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 403, in _no_args_handler
    return command_handlers[command](options)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 601, in command_update
    skip_eol_distros=not options.include_eol_distros)
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 497, in update_sources_list
    rosdep_data = get_gbprepo_as_rosdep_data(dist_name)
  File "/usr/lib/python2.7/dist-packages/rosdep2/gbpdistro_support.py", line 150, in get_gbprepo_as_rosdep_data
    ctx = create_default_installer_context()
  File "/usr/lib/python2.7/dist-packages/rosdep2/__init__.py", line 89, in create_default_installer_context
    m.register_platforms(context)
  File "/usr/lib/python2.7/dist-packages/rosdep2/platforms/debian.py", line 55, in register_platforms
    register_elementary(context)
  File "/usr/lib/python2.7/dist-packages/rosdep2/platforms/debian.py", line 82, in register_elementary
    (os_name, os_version) = context.get_os_name_and_version()
  File "/usr/lib/python2.7/dist-packages/rosdep2/installers.py", line 115, in get_os_name_and_version
    os_name = self.os_detect.get_name()
  File "/usr/lib/python2.7/dist-packages/rospkg/os_detect.py", line 684, in get_name
    self.detect_os()
  File "/usr/lib/python2.7/dist-packages/rospkg/os_detect.py", line 654, in detect_os
    raise OsNotDetected("Could not detect OS, tried %s" % attempted)
OsNotDetected: Could not detect OS, tried ['windows', 'clearlinux', 'ubuntu', 'slackware', 'rhel', 'qnx', 'osx', 'tizen', 'opensuse', 'opensuse', 'opensuse', 'openembedded', 'neon', 'mx', 'mint', 'linaro', 'gentoo', 'funtoo', 'freebsd', 'fedora', 'elementary', 'elementary', 'debian', 'cygwin', 'centos', 'manjaro', 'arch', 'alpine']

Installed OS: Zorin OS 15 (https://zorinos.com/) Which is built on Ubuntu 18.04 Bionic.

**Comment by tfoote** [comment]
As we don't test on Zorin regularly it's unlikely that we'll have a chance to do this. But if you'd like to contribute a detector to rospkg that would be appreciated. 

There's a little bit of documentation in the developer guide: http://docs.ros.org/independent/api/rosdep/html/developers_guide.html

A detector needs to be added here: https://github.com/ros-infrastructure/rospkg/blob/master/src/rospkg/os_detect.py

And then you'll need to add a rosdep alias as done here: https://github.com/ros-infrastructure/rosdep/blob/ab1f06ed84ee1e716eb611457b1168710415ea7a/src/rosdep2/platforms/debian.py#L54
