### ISSUE TITLE
Fails to detect opensuse on Leap 15.1

### ISSUE THREAD

**Issue by hemna** [ros-infrastructure/rosdep#704]
I just installed rosdep on my leap 15.1 vm

```
vagrant@localhost:~: $  sudo rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Warning: running 'rosdep update' as root is not recommended.
  You should run 'sudo rosdep fix-permissions' and invoke 'rosdep update' again without sudo.
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Add distro "crystal"

ERROR: Rosdep experienced an error: Could not detect OS, tried ['windows', 'nixos', 'clearlinux', 'ubuntu', 'slackware', 'rhel', 'qnx', 'osx', 'tizen', 'opensuse', 'opensuse', 'opensuse', 'openembedded', 'neon', 'mx', 'mint', 'linaro', 'gentoo', 'funtoo', 'freebsd', 'fedora', 'elementary', 'elementary', 'debian', 'cygwin', 'centos', 'manjaro', 'arch', 'alpine']
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.15.2

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/rosdep2/main.py", line 140, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python3.6/site-packages/rosdep2/main.py", line 394, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
  File "/usr/lib/python3.6/site-packages/rosdep2/main.py", line 403, in _no_args_handler
    return command_handlers[command](options)
  File "/usr/lib/python3.6/site-packages/rosdep2/main.py", line 601, in command_update
    skip_eol_distros=not options.include_eol_distros)
  File "/usr/lib/python3.6/site-packages/rosdep2/sources_list.py", line 497, in update_sources_list
    rosdep_data = get_gbprepo_as_rosdep_data(dist_name)
  File "/usr/lib/python3.6/site-packages/rosdep2/gbpdistro_support.py", line 150, in get_gbprepo_as_rosdep_data
    ctx = create_default_installer_context()
  File "/usr/lib/python3.6/site-packages/rosdep2/__init__.py", line 89, in create_default_installer_context
    m.register_platforms(context)
  File "/usr/lib/python3.6/site-packages/rosdep2/platforms/debian.py", line 55, in register_platforms
    register_elementary(context)
  File "/usr/lib/python3.6/site-packages/rosdep2/platforms/debian.py", line 82, in register_elementary
    (os_name, os_version) = context.get_os_name_and_version()
  File "/usr/lib/python3.6/site-packages/rosdep2/installers.py", line 115, in get_os_name_and_version
    os_name = self.os_detect.get_name()
  File "/usr/lib/python3.6/site-packages/rospkg/os_detect.py", line 685, in get_name
    self.detect_os()
  File "/usr/lib/python3.6/site-packages/rospkg/os_detect.py", line 655, in detect_os
    raise OsNotDetected("Could not detect OS, tried %s" % attempted)
rospkg.os_detect.OsNotDetected: Could not detect OS, tried ['windows', 'nixos', 'clearlinux', 'ubuntu', 'slackware', 'rhel', 'qnx', 'osx', 'tizen', 'opensuse', 'opensuse', 'opensuse', 'openembedded', 'neon', 'mx', 'mint', 'linaro', 'gentoo', 'funtoo', 'freebsd', 'fedora', 'elementary', 'elementary', 'debian', 'cygwin', 'centos', 'manjaro', 'arch', 'alpine']


vagrant@localhost:~: $  lsb_release -a
LSB Version:	n/a
Distributor ID:	openSUSE
Description:	openSUSE Leap 15.1
Release:	15.1
Codename:	n/a
```

**Comment by tfoote** [comment]
The os detection is from the rospkg module. https://github.com/ros-infrastructure/rospkg Please see if you can contribute an update to the detector that will detect Leap

You can see other OpenSUSE PRs here: https://github.com/ros-infrastructure/rospkg/pulls?q=is%3Apr+opensuse+is%3Aclosed
