### ISSUE TITLE
ROS_PYTHON_VERSION is unset. Defaulting to 2

### ISSUE THREAD

**Issue by iroshanvidanage** [ros-infrastructure/rosdep#743]
rosdep version: 0.18.0

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 144, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 428, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 524, in _package_args_handler
    lookup = _get_default_RosdepLookup(options)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 134, in _get_default_RosdepLookup
    verbose=options.verbose)
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 585, in create_default
    sources = load_cached_sources_list(sources_cache_dir=sources_cache_dir, verbose=verbose)
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 543, in load_cached_sources_list
    with open(cache_index, 'r') as f:
IOError: [Errno 13] Permission denied: '/home/iroshan/.ros/rosdep/sources.cache/index'

Please help me with this.....

**Comment by tfoote** [comment]
This looks like you have the incorrect permissions set for you cache directory like this: https://answers.ros.org/question/175599/rosdep-update-permission-error/

Please look at that and a few other questions with similar problems https://www.google.com/search?q=rosdep+permission+denied

If not then please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
