### ISSUE TITLE
catkin build error: UnicodeEncodeError

### ISSUE THREAD

**Issue by MagnusCardell** [ros-infrastructure/rosdep#758]
Hello,
Was developing a plugin for Gazebo when I discovered I no longer could build my catkin workspace. Running command:

`catkin build`

```
.
.
.
--------------------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/bin/catkin", line 11, in <module>
    load_entry_point('catkin-tools==0.4.5', 'console_scripts', 'catkin')()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 272, in main
    catkin_main(sysargs)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 267, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 422, in main
    summarize_build=opts.summarize  # Can be True, False, or None
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 283, in build_isolated_workspace
    workspace_packages = find_packages(context.source_space_abs, exclude_subspaces=True, warnings=[])
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 87, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 148, in find_packages_allowing_duplicates
    xml, filename=filename, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 710, in parse_package_string
    export.attributes[str(key)] = str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 5: ordinal not in range(128)
```

Same error occurs with this command:

`rosdep install --from-paths src --ignore-src --rosdistro melodic -y`

I am running Ubuntu 18.04.4 LTS using melodic distro. Let me know if I can complement with any more information

**Comment by MagnusCardell** [comment]
Not an issue anymore. Looking up the character u'\xa7' = "§" and searching for it in my package.xml files found the character. Edit/remove it and everything works fine again.
