### ISSUE TITLE
ERROR: Rosdep experienced an error: cannot import name OS_NIXOS

### ISSUE THREAD

**Issue by sensuir** [ros-infrastructure/rosdep#778]
I had install cartographer on my virturl machine(VMware workstation 16),  just follow the **https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html#building-installation**

but when i input the command as below, the system report an error: 
`

rosdep update                                                            
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Add distro "dashing"

ERROR: Rosdep experienced an error: cannot import name OS_NIXOS
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.19.0

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 144, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 428, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 437, in _no_args_handler
    return command_handlers[command](options)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 649, in command_update
    ros_distro=options.ros_distro)
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 507, in update_sources_list
    rosdep_data = get_gbprepo_as_rosdep_data(dist_name)
  File "/usr/lib/python2.7/dist-packages/rosdep2/gbpdistro_support.py", line 150, in get_gbprepo_as_rosdep_data
    ctx = create_default_installer_context()
  File "/usr/lib/python2.7/dist-packages/rosdep2/__init__.py", line 63, in create_default_installer_context
    from .platforms import nix
  File "/usr/lib/python2.7/dist-packages/rosdep2/platforms/nix.py", line 31, in <module>
    from rospkg.os_detect import OS_NIXOS
ImportError: cannot import name OS_NIXOS`

**Comment by nuclearsandwich** [comment]
What version of rospkg is installed? NixOS support was added in version 1.1.0 via ros-infrastructure/rospkg#171?
