### ISSUE TITLE
ERROR: Rosdep experienced an error: 'utf8' codec can't decode byte #xfc: invalid start byte   in "<string>", position 46011

### ISSUE THREAD

**Issue by junkhiang** [ros-infrastructure/rosdep#781]
ERROR: Rosdep experienced an error: 'utf8' codec can't decode byte #xfc: invalid start byte
  in "<string>", position 46011
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.19.0

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 144, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 428, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 437, in _no_args_handler
    return command_handlers[command](options)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 649, in command_update
    ros_distro=options.ros_distro)
  File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 507, in update_sources_list
    rosdep_data = get_gbprepo_as_rosdep_data(dist_name)
  File "/usr/lib/python2.7/dist-packages/rosdep2/gbpdistro_support.py", line 149, in get_gbprepo_as_rosdep_data
    distro_file = get_release_file(gbpdistro)
  File "/usr/lib/python2.7/dist-packages/rosdep2/rosdistrohelper.py", line 76, in get_release_file
    dist_file = rosdistro.get_distribution_file(get_index(), distro)
  File "/usr/lib/python2.7/dist-packages/rosdistro/__init__.py", line 119, in get_distribution_file
    data = _get_dist_file_data(index, dist_name, 'distribution')
  File "/usr/lib/python2.7/dist-packages/rosdistro/__init__.py", line 202, in _get_dist_file_data
    data.append(_load_yaml_data(u))
  File "/usr/lib/python2.7/dist-packages/rosdistro/__init__.py", line 195, in _load_yaml_data
    return yaml.safe_load(yaml_str)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/usr/lib/python2.7/dist-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 81, in __init__
    self.determine_encoding()
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 137, in determine_encoding
    self.update(1)
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 170, in update
    exc.encoding, exc.reason)
ReaderError: 'utf8' codec can't decode byte #xfc: invalid start byte
  in "<string>", position 46011

**Comment by nuclearsandwich** [comment]
Can you share the contents of your rosdep sources list?
