### ISSUE TITLE
Internal Parser Error in "_update_location_cache"

### ISSUE THREAD

**Issue by SRFG-MAT** [ros-infrastructure/rosdep#825]
Following the installation tutorial on Raspberry Pi 3 (Raspbian Jessie&Stretch) presented in the following guide:
http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi

From chapter 3.2.2 onwards when trying to use rosdep install, will result in an internal parse error in function "_update_location_cache". Problem has been posted before here: https://question1950.rssing.com/chan-34073207/article20-live.html.

`
Traceback (most recent call last):
  File "qbo_action_server.py", line 101, in <module>
    rospy.init_node('qbo')
  File "/usr/lib/python2.7/dist-packages/rospy/client.py", line 309, in init_node
    rospy.core.configure_logging(resolved_node_name)
  File "/usr/lib/python2.7/dist-packages/rospy/core.py", line 300, in configure_logging
    _log_filename = rosgraph.roslogging.configure_logging('rospy', level, filename=filename)
  File "/usr/lib/python2.7/dist-packages/rosgraph/roslogging.py", line 107, in configure_logging
    rosgraph_d = rospkg.RosPack().get_path('rosgraph')
  File "/usr/local/lib/python2.7/dist-packages/rospkg/rospack.py", line 205, in get_path
    self._update_location_cache()
  File "/usr/local/lib/python2.7/dist-packages/rospkg/rospack.py", line 188, in _update_location_cache
    list_by_path(self._manifest_name, path, cache)
  File "/usr/local/lib/python2.7/dist-packages/rospkg/rospack.py", line 71, in list_by_path
    root = ElementTree(None, os.path.join(d, PACKAGE_FILE))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 611, in __init__
    self.parse(file)
  File "<string>", line 38, in parse
cElementTree.ParseError: XML or text declaration not at start of entity: line 2, column 0
`

**Comment by tfoote** [comment]
This is not the same error.  You've filed this under rosdep, but `rosdep` does not appear in your traceback. You're actually running something with rospy. Your error appears to be that you have an invalid xml file which is the same as the other question but definitely not the same traceback. 

Please ask for help on on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

When you ask make sure to include what platform are you running on? And what versions of python libraries do you have installed (aka pip freeze) ? You appear to have rospkg installed from pip while you have most other things from debian packages. 

Please provide your all the commands to reproduce your problem and your workspace.
