### ISSUE TITLE
rosdep install --from-paths src --ignore-src -r -y

### ISSUE THREAD

**Issue by botaio** [ros-infrastructure/rosdep#854]
ERROR: Rosdep experienced an error: rosdep OS definition for [python3-pykdl:ubuntu] must be a dictionary, string, or list: None
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.8

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 137, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 383, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 477, in _package_args_handler
    return command_handlers[command](lookup, packages, options)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 665, in command_install
    uninstalled, errors = installer.get_uninstalled(packages, implicit=options.recursive, verbose=options.verbose)
  File "/usr/lib/python2.7/dist-packages/rosdep2/installers.py", line 440, in get_uninstalled
    resolutions, errors = self.lookup.resolve_all(resources, installer_context, implicit=implicit)
  File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 391, in resolve_all
    self.resolve(rosdep_key, resource_name, installer_context)
  File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 473, in resolve
    installer_key, rosdep_args_dict = definition.get_rule_for_platform(os_name, os_version, installer_keys, default_key)
  File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 140, in get_rule_for_platform
    raise InvalidData("rosdep OS definition for [%s:%s] must be a dictionary, string, or list: %s"%(self.rosdep_key, os_name, data), origin=self.origin)
InvalidData: rosdep OS definition for [python3-pykdl:ubuntu] must be a dictionary, string, or list: None

**Comment by tfoote** [comment]
This is an error in your rosdep sources format. Please ask a question on answers.ros.org listing all your rosdep sources and their contents.
