### ISSUE TITLE
rosdep init error on windows for noetic

### ISSUE THREAD

**Issue by wmpeets** [ros-infrastructure/rosdep#864]
ERROR: Rosdep experienced an error: module 'os' has no attribute 'geteuid'
Please go to the rosdep page [1] and file a bug report with the stack trace bel
ow.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.21.0

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\rosdep2\main.py", line 146, in rosdep_mai
n
    exit_code = _rosdep_main(args)
  File "c:\python38\lib\site-packages\rosdep2\main.py", line 441, in _rosdep_ma
in
    return _no_args_handler(command, parser, options, args)
  File "c:\python38\lib\site-packages\rosdep2\main.py", line 450, in _no_args_h
andler
    return command_handlers[command](options)
  File "c:\python38\lib\site-packages\rosdep2\main.py", line 659, in command_up
date
    update_sources_list(success_handler=update_success_handler,
  File "c:\python38\lib\site-packages\rosdep2\sources_list.py", line 516, in up
date_sources_list
    rosdep_data = get_gbprepo_as_rosdep_data(dist_name)
  File "c:\python38\lib\site-packages\rosdep2\gbpdistro_support.py", line 150,
in get_gbprepo_as_rosdep_data
    ctx = create_default_installer_context()
  File "c:\python38\lib\site-packages\rosdep2\__init__.py", line 85, in create_
default_installer_context
    m.register_installers(context)
  File "c:\python38\lib\site-packages\rosdep2\platforms\source.py", line 53, in
 register_installers
    context.set_installer(SOURCE_INSTALLER, SourceInstaller())
  File "c:\python38\lib\site-packages\rosdep2\platforms\source.py", line 201, i
n __init__
    super(SourceInstaller, self).__init__(source_detect, supports_depends=True)

  File "c:\python38\lib\site-packages\rosdep2\installers.py", line 328, in __in
it__
    self.sudo_command = 'sudo -H' if os.geteuid() != 0 else ''
AttributeError: module 'os' has no attribute 'geteuid'

**Comment by cottsay** [comment]
Fixed by #811, which hasn't been released yet.
