### ISSUE TITLE
Rosdep broken after 0.22 release

### ISSUE THREAD

**Issue by vatanaksoytezer** [ros-infrastructure/rosdep#886]
We are experiencing CI failures across ros-planning organization on all ROS2 distros with the new rosdep version (0.22). It seems it cannot find / install the rospkg module. An example passing and failing CI runs are below respectively:

Pass: https://github.com/PickNikRobotics/rviz_visual_tools/actions/runs/2391349400/attempts/1
Fail: https://github.com/PickNikRobotics/rviz_visual_tools/runs/7046842854?check_suite_focus=true

Copying the error message we are getting below:

```
$ sudo rosdep init > /dev/null 
  Traceback (most recent call last):
    File "/usr/bin/rosdep", line 6, in <module>
      from pkg_resources import load_entry_point
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
      def _initialize_master_working_set():
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3[241](https://github.com/PickNikRobotics/rviz_visual_tools/runs/7046842854?check_suite_focus=true#step:5:246), in _call_aside
      f(*args, **kwargs)
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
      working_set = WorkingSet._build_master()
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
      ws.require(__requires__)
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
      needed = self.resolve(parse_requirements(requirements))
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
      raise DistributionNotFound(req, requirers)
  pkg_resources.DistributionNotFound: The 'rospkg>=1.4.0' distribution was not found and is required by rosdep
  'sudo rosdep init > /dev/null ' returned with 1
```

I didn't go deep down to find out the root cause, just wanted to quickly notify folks on this.

**Comment by cottsay** [comment]
Thanks for the quick report. From what I can tell, this is a problem in our approach for packaging debs for Python 2 and Python 3 simultaneously. It shouldn't affect folks who install from pip or RPMs.

I'll start digging around for a solution - I'm not sure yet if the problem is in `rosdep` or `rospkg`. A workaround would be to install `python3-rospkg`.

**Comment by cottsay** [comment]
@vatanaksoytezer - rosdep 0.22.1 has been pushed to the ROS repositories. Please re-open this issue if you continue to see problems.

**Comment by vatanaksoytezer** [comment]
@cottsay thank you so much for fixing this so quickly and releasing it. Our CIs are back to normal now!
