### ISSUE TITLE
Multiple packages found with the same name "depthai_examples"

### ISSUE THREAD

**Issue by alphalambdaepsilonxi** [ros-infrastructure/rosdep#897]
ERROR: Rosdep experienced an error: Multiple packages found with the same name "depthai_examples":
- luxonis/depthai-ros-examples/depthai_examples
- luxonis/depthai-ros/depthai_examples
**Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep**

rosdep version: 0.22.1

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 146, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 446, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 501, in _package_args_handler
    pkgs = find_catkin_packages_in(path, options.verbose)
  File "/usr/lib/python3/dist-packages/rosdep2/catkin_packages.py", line 35, in find_catkin_packages_in
    packages = find_packages(path)
  File "/usr/lib/python3/dist-packages/catkin_pkg/packages.py", line 103, in find_packages
    raise RuntimeError('\n'.join(duplicates))
RuntimeError: Multiple packages found with the same name "depthai_examples":
- luxonis/depthai-ros-examples/depthai_examples
- luxonis/depthai-ros/depthai_examples

**Comment by christophebedard** [comment]
This is not `rosdep`'s fault. You cannot have two packages with the same name. Remove one of them and try again.
