### ISSUE TITLE
Unrecognized Version: 13 

### ISSUE THREAD

**Issue by Marco-Gonzales** [ros-infrastructure/rosdep#914]
I am trying to run "rosdep update" and this is the error I am receiving:

MacBook-Air:sources.list.d Marco$ rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Skip end-of-life distro "dashing"
Skip end-of-life distro "eloquent"
Add distro "foxy"

ERROR: Rosdep experienced an error: unrecognized version: 13
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.22.1

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rosdep2/main.py", line 146, in rosdep_main
    exit_code = _rosdep_main(args)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rosdep2/main.py", line 444, in _rosdep_main
    return _no_args_handler(command, parser, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rosdep2/main.py", line 453, in _no_args_handler
    return command_handlers[command](options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rosdep2/main.py", line 664, in command_update
    update_sources_list(success_handler=update_success_handler,
  File "/usr/local/lib/python3.11/site-packages/rosdep2/sources_list.py", line 508, in update_sources_list
    rosdep_data = get_gbprepo_as_rosdep_data(dist_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rosdep2/gbpdistro_support.py", line 148, in get_gbprepo_as_rosdep_data
    ctx = create_default_installer_context()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rosdep2/__init__.py", line 91, in create_default_installer_context
    m.register_platforms(context)
  File "/usr/local/lib/python3.11/site-packages/rosdep2/platforms/arch.py", line 53, in register_platforms
    register_manjaro(context)
  File "/usr/local/lib/python3.11/site-packages/rosdep2/platforms/arch.py", line 58, in register_manjaro
    (os_name, os_version) = context.get_os_name_and_version()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rosdep2/installers.py", line 115, in get_os_name_and_version
    os_name = self.os_detect.get_name()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rospkg/os_detect.py", line 634, in get_name
    self.detect_os()
  File "/usr/local/lib/python3.11/site-packages/rospkg/os_detect.py", line 596, in detect_os
    self._os_codename = os_detector.get_codename()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rospkg/os_detect.py", line 351, in get_codename
    return _osx_codename(*ver[0:2])
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rospkg/os_detect.py", line 329, in _osx_codename
    raise OsNotDetected("unrecognized version: %s" % key)
rospkg.os_detect.OsNotDetected: unrecognized version: 13

I do not know how to fix this please help.

**Comment by ijnek** [comment]
Hi @Marco-Gonzale , thanks for opening this issue.
This seems like an issue in the underlying [rospkg](https://github.com/ros-infrastructure/rospkg) library and that it doesn't detect MacOS Ventura yet because it is new. There seems to be a fix ready to be merged in - https://github.com/ros-infrastructure/rospkg/pull/256.

A dirty work around until the changes are merged and released, would be to manualy edit ``/usr/local/lib/python3.11/site-packages/rospkg/os_detect.py`` and apply the changes from https://github.com/ros-infrastructure/rospkg/pull/256.
