### ISSUE TITLE
rosdep install --from-paths src --ignore-src -r -y not working

### ISSUE THREAD

**Issue by wscott20** [ros-infrastructure/rosdep#988]
Whenever i try to run `rosdep install --from-paths src --ignore-src -r -y` to install dependencies I added via `git clone` (I'm on a mac so i had to use git clone to install ros2 and rcl ament etc) but it kept saying
```
Error: No available formula with the name "ros/humble/googletest".
Please tap it and then try again: brew tap ros/humble

ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.25.1

Bad installer [homebrew]: Error while parsing brew info for 'ros/humble/googletest'
 * Output of `brew info ros/humble/googletest --json=v1`:
 
 * Error while parsing:
 Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rosdep2/platforms/osx.py", line 203, in is_installed
    pkg_info = json.loads(std_out)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I tried `brew tap ros/humble` and `brew tap ros2/humble` but it said
```
==> Tapping ros/humble
Cloning into '/usr/local/Homebrew/Library/Taps/ros/homebrew-humble'...
remote: Repository not found.
fatal: repository 'https://github.com/ros/homebrew-humble/' not found
Error: Failure while executing; `git clone https://github.com/ros/homebrew-humble /usr/local/Homebrew/Library/Taps/ros/homebrew-humble --origin=origin --template= --config core.fsmonitor=false` exited with 128.
```

**Comment by becschwartz** [comment]
Hello,

What's in your /etc/ros/rosdep/sources.list.d directory?
