### ISSUE TITLE
rosdep install -i --from-path src --rosdistro humble -y

### ISSUE THREAD

**Issue by IHATEDATA** [ros-infrastructure/rosdep#989]
ERROR: Rosdep experienced an error: rosdep data for [release-name] must be a dictionary
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.21.0

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 146, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 442, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 551, in _package_args_handler
    return command_handlers[command](lookup, packages, options)
  File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 755, in command_install
    uninstalled, errors = installer.get_uninstalled(packages, implicit=options.recursive, verbose=options.verbose)
  File "/usr/lib/python3/dist-packages/rosdep2/installers.py", line 445, in get_uninstalled
    resolutions, errors = self.lookup.resolve_all(resources, installer_context, implicit=implicit)
  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 400, in resolve_all
    rosdep_keys = self.get_rosdeps(resource_name, implicit=implicit)
  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 318, in get_rosdeps
    return self.loader.get_rosdeps(resource_name, implicit=implicit)
  File "/usr/lib/python3/dist-packages/rosdep2/rospkg_loader.py", line 144, in get_rosdeps
    if resource_name in self.get_catkin_paths():
  File "/usr/lib/python3/dist-packages/rosdep2/rospkg_loader.py", line 133, in get_catkin_paths
    self._catkin_packages_cache = dict(find_catkin_paths(self._rospack))
  File "/usr/lib/python3/dist-packages/rosdep2/rospkg_loader.py", line 132, in <lambda>
    filter(lambda x: src.get_manifest(x).is_catkin, src.list()))
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 171, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 215, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/python3/dist-packages/rospkg/manifest.py", line 414, in parse_manifest_file
    _static_rosdep_view = init_rospack_interface()
  File "/usr/lib/python3/dist-packages/rosdep2/rospack.py", line 61, in init_rospack_interface
    return lookup.get_rosdep_view(DEFAULT_VIEW_KEY)
  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 625, in get_rosdep_view
    view = self.create_rosdep_view(view_key, dependencies + [view_key], verbose=verbose)
  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 570, in create_rosdep_view
    view.merge(db_entry, verbose=verbose)
  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 224, in merge
    update_definition = RosdepDefinition(dep_name, dep_data, update_entry.origin)
  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 66, in __init__
    raise InvalidData('rosdep data for [%s] must be a dictionary' % (self.rosdep_key), origin=origin)
rosdep2.core.InvalidData: rosdep data for [release-name] must be a dictionary

**Comment by tfoote** [comment]
It looks like you have invalid data in your rosdep sources:

`rosdep2.core.InvalidData: rosdep data for [release-name] must be a dictionary`

We should update rosdep to not to report an internal error when data validation fails.
